import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";
import NextTopLoader from 'nextjs-toploader'
import SmoothScrollProvider from "@/components/provider/SmoothScrollProvider";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Auto Intel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={manrope.className}>
      <body className="font-manrope antialiased">
      <NextTopLoader color="#FBBF24" height={3} showSpinner={false} />
      <SmoothScrollProvider>
        {children}
        </SmoothScrollProvider>
      </body>
    </html>
  );
}